DROP TABLE RESERVATION;
DROP TABLE TABLES;
DROP TABLE USER;

CREATE TABLE TABLES (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	CAPACITY INT,
	MAX_PERIOD INT
);

CREATE TABLE USER (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(250) NOT NULL
);

CREATE TABLE RESERVATION (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	TABLE_ID INT,
	USER_ID INT,
	DATETIME TIMESTAMP,
	DURATION INT,
	SEATS INT,
	FOREIGN KEY(TABLE_ID) REFERENCES TABLES(ID),
	FOREIGN KEY(USER_ID) REFERENCES USER(ID),
	UNIQUE KEY(TABLE_ID, USER_ID, DATETIME)
);

INSERT INTO TABLES(CAPACITY, MAX_PERIOD)
VALUES(2, 60);
INSERT INTO TABLES(CAPACITY, MAX_PERIOD)
VALUES(4, 120);
INSERT INTO TABLES(CAPACITY, MAX_PERIOD)
VALUES(6, 180);
INSERT INTO TABLES(CAPACITY, MAX_PERIOD)
VALUES(10, 240);
INSERT INTO TABLES(CAPACITY, MAX_PERIOD)
VALUES(16, 300);

INSERT INTO USER(NAME)
VALUES('REENA');
INSERT INTO USER(NAME)
VALUES('MUKESH');
INSERT INTO USER(NAME)
VALUES('KUMAR');
INSERT INTO USER(NAME)
VALUES('RAJ');
INSERT INTO USER(NAME)
VALUES('KUNAL');
INSERT INTO USER(NAME)
VALUES('RASHMI');
INSERT INTO USER(NAME)
VALUES('NILESH');
INSERT INTO USER(NAME)
VALUES('MANOJ');
INSERT INTO USER(NAME)
VALUES('SONAL');

